### ISSUE TITLE
segmentation fault with sample z score and LD data

### ISSUE THREAD

**Issue by matthiasheinig** [xqwen/dap#13]
Hi,
I am encountering a problem when running the code I checked out and compiled today. Any idea what could be the problem?
Best,
Matthias

./dap-g -d_z sample_data/sim.1.zval.dat -d_ld sample_data/sim.1.LD.dat 

============ DAP Configuration ============

INPUT

        * summary-level data (z-scores and LD matrix)
        * number of candidate SNPs: 1001

PROGRAM OPTIONS

        * maximum model size allowed [-msize]: 1001 (no restriction)
        * LD control threshold [-ld_control]: 0.25
        * normalizing constant convergence threshold [-converg_thresh]: 1.00e-02 (log10 scale)

RUN LOG

        Model_Size      candidates        log10(NC)
Segmentation fault (core dumped)

**Comment by xqwen** [comment]
Thanks very much for reporting this. It is a bug introduced by some of the new features we introduced recently for complete data and sufficient summary stats input.  I have pushed a quick fix.  

Thanks again!

William

**Comment by matthiasheinig** [comment]
Thank you very much for the quick response, the set fault is gone now :)
