### ISSUE TITLE
No cluster output

### ISSUE THREAD

**Issue by matthiasheinig** [xqwen/dap#15]
Hi,
I am trying to use dap together with fastenloc. The perl script that summarizes the dap output expects to find cluster level output in the file. However, in my analysis of z-scores, I do not get any clusters (all SNPs are in cluster -1). How could I solve this issue? 

Could I tune some parameters to get clusters?

Or, if indeed all SNPs are independent, can the output of cluster information (containing only one SNP) be enforced?

Thanks for your assistance

Best,
Matthias

**Comment by xqwen** [comment]
This simply means there are no noteworthy association signals detected in the given data. 

You should be able to inspect the single-SNP z-scores or Bayes factors (by running dap-g with --scan option) to get a sense if an association signal likely exists. 
 
Increasing the SNP-level prior  (via -pi1 option) would help lower the threshold for signal clusters. The default prior pi1 is 1/p  with p being the number of SNPs in the input.  But note that making pi1 too liberal can increase false positives. 

Finally, with the "--dap1" option, dap-g will force all SNPs into a single cluster, which mimics the behavior of fgwas. This option, however, lacks the ability to identify multiple independent signals. 

Best,
William

**Comment by matthiasheinig** [comment]
Hi William,
thanks for your reply. I have an eQTL with z = -5.7453 which gives me a Bayes factor of 178.715 (is this the correct interpretation of the second column of the --scan output?). The SNP level PIP is 58%. Would you call this an association signal or not?
Best,
Matthias

**Comment by matthiasheinig** [comment]
Hi William,
I checked further the input and I was wondering why the SNP mentioned above was given maximal pip by the model - there are actually quite a few stronger z-scores (up to 20) in the data (large meta analysis). Could there be some numerical issues with these very large z scores? If you want I can share the input data..
Best,
Matthias

**Comment by matthiasheinig** [comment]
Hi William,

regarding my last comment: I think I found the reason - the alleles in my plink file were not always encoded the same as for the summary stats, so the signs fo the z-scores did not fit with the correlations.. I flipped the alleles and now I get the strongest signals and also cluster output..
I think that solves the case..

Best,
Matthias
