### ISSUE TITLE
-p prior_file format

### ISSUE THREAD

**Issue by adrtin** [xqwen/dap#26]
DAP-G worked well in my project.
I would like to add prior estimated from functional annotation.
Could you please provide some documentation on the file format required for the -p option?
Is the prior a value from 0 to 1 for each variant with 0 indicating low probability of being causal?
Providing an example prior data file would be great too.

Thank you

**Comment by xqwen** [comment]
Sure. The format is pretty simple and described in [here](https://github.com/xqwen/dap/tree/master/dap_src#42-prior-specifications). Basically, the file should be a two-column text file, where the first column represents SNP names and the second column represents the probabilities.

If you use [TORUS](https://github.com/xqwen/torus/) to generate the informative priors, the output can be directly used by DAP.

**Comment by adrtin** [comment]
Thank you.
