### ISSUE TITLE
`dap1` source

### ISSUE THREAD

**Issue by Heroico** [xqwen/dap#7]
Hi there!
I would need the sources for the binary `version1/dap1_src/dap1`, so that the system administrator at my organization can install it on our cluster. Is there any chance of getting it?

I had mixed success using  a binary I built from `version1/dap_src` as a replacement. Should both of them work similarly for enloc?

Thanks!

**Comment by xqwen** [comment]
It looks like a stupid mistake we made when archiving the code from the previous version. Thanks very much for reporting it. The source code has been restored in version1/dap1_src.

**Comment by Heroico** [comment]
Great, thanks a lot!
